### ISSUE TITLE
Avoid large JSON file in repo

### ISSUE THREAD

**Issue by danleh** [mkustermann/wasm_gc_benchmarks#3]
For the V8 performance regression tests, I'd like to import this but avoid the ~80MB `data/devtools_cpu_samples.json` file. Could we do the following (sketch, not a Dart expert):

- Compress the JSON file with gzip: `gzip -9 data/devtools_cpu_samples.json` (compresses down to 4.3MB) and then
- Patch `parse_cpu_samples.dart` to do something like
```dart
// ARGS=data/devtools_cpu_samples.json.gz
[...]
import 'dart:convert';
import 'dart:io';
[...]
  final JSUint8Array jsBytes = Uint8List.fromList(
          gzip.decode(readFileContentsAsBytes(filename.toJS).toDart))
      .toJS;
  final JSString jsString = (utf8.decode(jsBytes.toDart).toJS);
```

**Comment by danleh** [comment]
Ah, I am the issue https://stackoverflow.com/a/74204108 with `dart:io`'s gzip decoder, but this works:
```dart
import 'package:archive/archive_io.dart';
[...]
final JSUint8Array jsBytes = Uint8List.fromList(GZipDecoder()
          .decodeBytes(readFileContentsAsBytes(filename.toJS).toDart))
      .toJS;
```

**Comment by mkustermann** [comment]
I can do the change and re-compile the checked-in wasm files with this change.

**Comment by danleh** [comment]
Awesome, thank you!

**Comment by mkustermann** [comment]
https://github.com/mkustermann/wasm_gc_benchmarks/commit/de1f6c3f39e9871b42e79435311554de2aa258a2 landed.
